apiVersion: v1
kind: ConfigMap
metadata:
  name: sub-imgs-configmap
data:
  IP: "10.10.2.220:30000"
  TOPIC: "Topic.Frame"
  IMAGE_FORMAT: "jpg"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-images
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/images"
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-images
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-imgs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub-imgs
  template:
    metadata:
      labels:
        app: sub-imgs
    spec:
      containers:
      - name: sub-imgs
        image: juniorgui/aula-is:v11
        envFrom:
        - configMapRef:
            name: sub-imgs-configmap
        volumeMounts:
        - mountPath: /data/images
          name: images-storage
      volumes:
      - name: images-storage
        persistentVolumeClaim:
          claimName: pvc-images
